---
- name: Установка репозитория заббикс
  apt:
    deb: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu24.04_all.deb"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Установка PostgreSQL и компонентов Zabbix
  apt:
    name:
      - postgresql
      - python3-psycopg2
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php-pgsql
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent
    state: present

- name: Создание пользователя БД Zabbix
  community.postgresql.postgresql_user:
    name: "{{ zabbix_db_user }}"
    password: "{{ zabbix_db_password }}" # group_vars/all.yml
    state: present
  become: yes
  become_user: postgres

- name: Создание БД Zabbix
  community.postgresql.postgresql_db:
    name: "{{ zabbix_db_name }}"
    owner: "{{ zabbix_db_user }}"
    encoding: UTF-8
    state: present
  become: yes
  become_user: postgres

- name: Проверка импорта схемы
  command: >
    psql -d {{ zabbix_db_name }} -tAc
    "SELECT 1 FROM information_schema.tables WHERE table_name='users';"
  become: yes
  become_user: postgres
  register: db_check
  changed_when: false


- name: Импорт схемы
  shell: |
    zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | \
    PGPASSWORD="{{ zabbix_db_password }}" \
    psql -h localhost -U {{ zabbix_db_user }} -d {{ zabbix_db_name }}
  when: db_check.stdout != "1"

- name: Настройка сервера Zabbix с помощью шаблона
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: zabbix
    group: zabbix
    mode: '0640'
  notify: restart zabbix-server

- name: Включение и запуск служб
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - postgresql
    - zabbix-server
    - apache2
    - zabbix-agent
