---
- name: Установка Docker SDK для Python (pip)
  become: true
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Установка библиотеки Docker для Python через APT
  ansible.builtin.apt:
    name: python3-docker
    state: present
    update_cache: yes

- name: Запуск Elasticsearch
  docker_container:
    name: elasticsearch
    image: elasticsearch:7.17.10
    state: started
    restart_policy: always
    published_ports:
      - "9200:9200"
      - "9300:9300"
    env:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "{{ kibana_password }}"
  notify: Recreate Elasticsearch Container