[all:vars]
ansible_user=rinat
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=accept-new rinat@158.160.49.5" -o StrictHostKeyChecking=accept-new'

[nginx-web]
nginx-1.ru-central1.internal
nginx-2.ru-central1.internal

[zabbix]
zabbix.ru-central1.internal

[elasticsearch]
elasticsearch.ru-central1.internal

[kibana]
kibana.ru-central1.internal
