---
- import_playbook: docker_install.yml

- import_playbook: elastic_deploy.yml

- import_playbook: zabbix_server.yml
- import_playbook: kibana_deploy.yml

- import_playbook: install_nginx.yml

- import_playbook: zabbix_agents.yml

- import_playbook: filebeat.yml
